'''
Created on 9. nov 2017

@author: Johan
'''
import copy


class SMPGameState():
	'''
	Implements the state of one game session
	'''

	_gid = 0  # Unique game id generated by the server
	_puzzle = None  # An instance of SMPPuzzle
	_cids = []  # A list of joined client id-s
	_max_player_count = 0  # Max number of players.
	# The game starts when all players have joined
	_scores = {}  # A dict of player's scores. Indexed by client id.

	_start_time = 0
	_end_time = 0


	def __init__(self, gid):
		'''
		Creates a unique game instance
		@param gid uint A unique game id
		'''
		self._gid = gid


	def get_game_info(self):
		gi = {}
		gi['gid'] = self._gid
		gi['cid_list'] = copy.deepcopy(self._cids)
		gi['max_players'] = self._max_player_count
		gi['scores'] = copy.deepcopy(self._scores)
		return gi


	def has_started(self):
		return self._start_time > 0

	def has_ended(self):
		return self._end_time > self._start_time
