'''
encoding: utf-8
Created on 2. nov 2017

@author: Johan
'''

# Set up logging
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s (%(threadName)-2s) [%(levelname)s] %(message)s')  # datefmt='%H:%M:%S.'
LOG = logging.getLogger('SMPLogger')

RPC_EXT = 'RPC'
SERVER_ID = 'SMPServer'
SERVER_RPC_NAME = SERVER_ID + RPC_EXT
CLIENT_HANDLER_ID = 'SMPClientHandler{}'
CLIENT_HANDLER_RPC_NAME = CLIENT_HANDLER_ID + RPC_EXT

DEFAULT_MESSAGE_TTL = 600  # seconds


class SMPException(Exception):
	'''
	Custom exception used for any exceptions
	generated by this application
	'''


class SMPSocketClosedException(SMPException):
	''' Used for detecting remote side socket closure '''
